# Licensed under the Apache-2.0 license

[toolchain]
channel = "1.85.1"
components = ["rustfmt", "clippy"]  # Add any additional components you need
profile = "minimal"  # Optional: You can set this to "minimal", "default", or "complete"
